meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: just_install_packages
    templates:
    - name: just_install_packages
      release: noop-cf
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( params "please set just_install_package networks" ))

networks: (( params "please set networks" ))

properties: {}
